### PR TITLE
Change build process and project structure

### PR DESCRIPTION
**Pull request by florianschmidt1994**
Hey everyone, I felt like cleaning this repo up a little bit.

Basic idea: All source code lives in `src/` and all distribution code in `dist/`. The `src/` folder is also split in three parts, `client`, `server` and common, where all respective code lives in those subfolders.

Also the build now only uses webpack and grunt can be completely dropped, so this is unified as well

Also I removed a lot of dead code that was not used at all anymore, so some folders have just disappeared completely

### CODE REVIEW

**Comment by florianschmidt1994** [comment]
Best way to check this out would probably be to check out my branch at florianschmidt1994/breakout-frontend and take a look at the new folder structure, because there were *a lot* of files moved from a to b. Maybe spin it up and see if it works for you?

**Comment by thepiwo** [comment]
looks good, I will have to try

**Comment by thepiwo** [comment]
why is the `dist/js/styles.css` committed?

**Comment by florianschmidt1994** [comment]
No reason, I removed it. Have you had a chance to try this out yet?

**Comment by thepiwo** [comment]
Sadly not, will try to do it this weekend

**Review by thepiwo — COMMENTED** [review]
1. move static content out of `/dist` folder and only copy there while bundling, so a `clean` could wipe `/dist`
2. are all the handlebar templates for registration/login still used or is all of it replaced by react?
3. `/src/client/js/*` files could be grouped into subfolders, e.g. for what is used as full pages or just util
4. `/src/server/controller/*` files could be grouped as well
5. `/src/server/controller/*` files naming could be uniformed
6. after running `npm run build` I get the error that `app.js` is not found for starting

**Comment by florianschmidt1994** [comment]
I think most of the comments should be addressed now @thepiwo, only regarding the handlebars templates: I would leave this up to another PR / Issue to go through those and delete unused ones

**Review by dominikglandorf — APPROVED** [review]
running, and looks better than before

**Review by thepiwo — APPROVED** [review]

**Pull request merged**
